# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MST
                                 A QGIS plugin
 This plugin creates minimum spanning trees in multiple ways.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-06
        copyright            : (C) 2019 by Murat ÇALIŞKAN
        email                : caliskan.murat.20@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MST class from file MST.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .minimum_spanning_trees import MST
    return MST(iface)
